/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokemonsimulator;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Lucas
 */
public class JFrameVencedor extends javax.swing.JFrame {

    /**
     * Creates new form JFrameVencedor
     * @param vencedor
     */
    String gymName;
    public JFrameVencedor(String vencedor, String gymName) {
        initComponents();
        this.gymName = gymName;
        this.setSize(650, 450);
        this.setResizable(false);
        btnBatalharNovamente.setFocusable(false);
        ImageIcon imgBackground = new ImageIcon(getClass().getResource("/fotos/" + gymName + ".png"));
        lblBackground.setIcon(new ImageIcon(imgBackground.getImage().getScaledInstance(lblBackground.getWidth(),lblBackground.getHeight(), Image.SCALE_DEFAULT)));
        btnBatalharNovamente.setFocusable(false);
        btnSair.setFocusable(false);
        
        
        String var;
        if (vencedor == null) {
            titleVencedor.setText("A batalha terminou em empate!");
            lblVencedor.setText("Que pena...");
            var = "/fotos/whismur.png";
        }
        else {
            titleVencedor.setText("O Vencedor é...");
            lblVencedor.setText(vencedor);
            var = "/fotos/" + vencedor + ".png";
        }
            ImageIcon image1 = new ImageIcon(getClass().getResource(var));
            imgVencedor.setIcon(new ImageIcon(image1.getImage().getScaledInstance(imgVencedor.getWidth(), imgVencedor.getHeight(), Image.SCALE_DEFAULT)));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        imgVencedor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titleVencedor = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblVencedor = new javax.swing.JLabel();
        btnBatalharNovamente = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(641, 380));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 160, 30));

        imgVencedor.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(imgVencedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 262, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        titleVencedor.setBackground(new java.awt.Color(255, 255, 255));
        titleVencedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleVencedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleVencedor.setFocusable(false);
        titleVencedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleVencedor, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 380, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblVencedor.setBackground(new java.awt.Color(255, 255, 255));
        lblVencedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVencedor.setForeground(new java.awt.Color(0, 0, 0));
        lblVencedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVencedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVencedor, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVencedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 180, 40));

        btnBatalharNovamente.setText("Batalhar novamente!");
        btnBatalharNovamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalharNovamenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalharNovamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 160, 30));
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 690, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalharNovamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalharNovamenteActionPerformed
        JFramePokemon jFramePokemon = new JFramePokemon(this.gymName);
        jFramePokemon.setVisible(true);
        jFramePokemon.setLocationRelativeTo(null);
        dispose();
        
    }//GEN-LAST:event_btnBatalharNovamenteActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalharNovamente;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel imgVencedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblVencedor;
    private javax.swing.JLabel titleVencedor;
    // End of variables declaration//GEN-END:variables
}
