/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokemonsimulator;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Lucas
 */
public class JFrameGym extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInicio
     */
    public JFrameGym() {
        
        initComponents();
        this.setSize(650, 450);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jRadioButton1.setFocusable(false);
        jRadioButton2.setFocusable(false);
        jRadioButton3.setFocusable(false);
        jRadioButton4.setFocusable(false);
        btnComecar.setFocusable(false);
        
        ImageIcon imgGymAgua = new ImageIcon(getClass().getResource("/fotos/gymAgua.png"));
        ImageIcon imgGymFogo = new ImageIcon(getClass().getResource("/fotos/gymFogo.png"));
        ImageIcon imgGymPedra = new ImageIcon(getClass().getResource("/fotos/gymPedra.png"));
        ImageIcon imgGymPlanta = new ImageIcon(getClass().getResource("/fotos/gymPlanta.png"));
        lblAgua.setIcon(new ImageIcon(imgGymAgua.getImage().getScaledInstance(lblAgua.getWidth(),lblAgua.getHeight(), Image.SCALE_DEFAULT)));
        lblFogo.setIcon(new ImageIcon(imgGymFogo.getImage().getScaledInstance(lblFogo.getWidth(),lblFogo.getHeight(), Image.SCALE_DEFAULT)));        
        lblPedra.setIcon(new ImageIcon(imgGymPedra.getImage().getScaledInstance(lblPedra.getWidth(),lblPedra.getHeight(), Image.SCALE_DEFAULT)));
        lblPlanta.setIcon(new ImageIcon(imgGymPlanta.getImage().getScaledInstance(lblPlanta.getWidth(),lblPlanta.getHeight(), Image.SCALE_DEFAULT)));
        //btnGymAgua.setIcon(imgGymAgua);
        
        //lblGymAgua.setIcon(new ImageIcon(image1.getImage().getScaledInstance(lblGymAgua.getWidth(),lblGymAgua.getHeight(), Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnComecar = new javax.swing.JButton();
        lblAgua = new javax.swing.JLabel();
        lblPedra = new javax.swing.JLabel();
        lblFogo = new javax.swing.JLabel();
        lblPlanta = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComecar.setText("Iniciar batalha!");
        btnComecar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 150, 30));
        jPanel1.add(lblAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 230, 120));
        jPanel1.add(lblPedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 230, 120));
        jPanel1.add(lblFogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 230, 120));
        jPanel1.add(lblPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 230, 120));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ginásio de Água");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ginásio de Fogo");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Ginásio de Pedra");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Ginásio de Planta");
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarActionPerformed

        String gymName = null;
        if (jRadioButton1.isSelected()) {
            gymName = "gymAguaIn";
        } else if (jRadioButton2.isSelected()) {
            gymName = "gymFogoIn";
        } else if (jRadioButton3.isSelected()) {
            gymName = "gymPedraIn";
        } else if (jRadioButton4.isSelected()) {
            gymName = "gymPlantaIn";

        }

        JFramePokemon jFramePokemon = new JFramePokemon(gymName);
        dispose();
    }//GEN-LAST:event_btnComecarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComecar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblFogo;
    private javax.swing.JLabel lblPedra;
    private javax.swing.JLabel lblPlanta;
    // End of variables declaration//GEN-END:variables
}
